//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH_TPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrunchTicket
    {
        public int TicketId { get; set; }
        public int GuestId { get; set; }
        public int BrunchRemaining { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
