//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH_TPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinibarItems
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public int ItemStock { get; set; }
        public int Deleted { get; set; }
        public int ItemMinimumStock { get; set; }
        public int ItemPrice { get; set; }
    }
}
