//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH_TPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeDish
    {
        public int DishId { get; set; }
        public int IngredientId { get; set; }
        public int Quantity { get; set; }
        public int Deleted { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
